table dim_state
	lineageTag: 6a6df96a-5540-4678-9302-afd9034ffdb6

	column state_key
		dataType: int64
		isHidden
		lineageTag: daef865d-eed4-4a35-b624-86a67021d6d1
		summarizeBy: none
		sourceColumn: state_key

	column State
		dataType: string
		lineageTag: 756cb186-3434-41d8-ad26-770cadf9d7f3
		summarizeBy: none
		sourceColumn: state_name
		sortByColumn: state_sort_order

	column 'State Category'
		dataType: string
		lineageTag: f15ac8ad-092f-4944-a2fb-c2fb243f589e
		summarizeBy: none
		sourceColumn: state_category

	column state_sort_order
		dataType: int64
		lineageTag: 4b01f226-38bc-4f80-9977-a65662f9a958
		summarizeBy: none
		sourceColumn: state_sort_order

	column is_waiting_state
		dataType: boolean
		lineageTag: 181a2899-925c-4cb8-aeb7-d853c3ea79d1
		summarizeBy: none
		sourceColumn: is_waiting_state

	partition dim_state = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_state.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"state_key", Int64.Type}, {"state_name", type text}, {"state_category", type text}, {"state_sort_order", Int64.Type}, {"is_waiting_state", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
