table dim_assignment_group
	lineageTag: 252bb796-28c5-4907-b9ef-5f09ce4bc49b

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: 8e37675b-290e-4dc1-b6aa-4779a0929e5e
		summarizeBy: none
		sourceColumn: assignment_group_key

	column 'Assignment Group'
		dataType: string
		lineageTag: ce29ff91-b677-4beb-b9ab-fe30298a5687
		summarizeBy: none
		sourceColumn: assignment_group_name

	partition dim_assignment_group = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_assignment_group.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"assignment_group_key", Int64.Type}, {"assignment_group_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
