table dim_resolver
	lineageTag: e105dc52-ce5d-48ee-90df-18cb88ca333b

	column resolver_key
		dataType: int64
		isHidden
		lineageTag: 8f042613-1cb2-43e9-9864-7a4408a18332
		summarizeBy: none
		sourceColumn: resolver_key

	column Resolver
		dataType: string
		lineageTag: 3aa2022b-118b-4609-b343-559962cbc642
		summarizeBy: none
		sourceColumn: resolver_name

	partition dim_resolver = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_resolver.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"resolver_key", Int64.Type}, {"resolver_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
