table dim_location
	lineageTag: 38c66f25-0a25-4d3e-9cbd-89188d3c9fec

	column location_key
		dataType: int64
		isHidden
		lineageTag: 55d1613a-380c-4342-b715-18f4fb9fe104
		summarizeBy: none
		sourceColumn: location_key

	column Location
		dataType: string
		lineageTag: 24848563-c89e-4c1d-bb13-79299f4c7324
		summarizeBy: none
		sourceColumn: location_name

	partition dim_location = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_location.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"location_key", Int64.Type}, {"location_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
