table dim_resolver
	lineageTag: 98d1eccd-107d-4d02-baf6-b9e148b29c03

	column resolver_key
		dataType: int64
		isHidden
		lineageTag: 490de296-c1aa-430a-b6e4-e47a9e59d01d
		summarizeBy: none
		sourceColumn: resolver_key

	column Resolver
		dataType: string
		lineageTag: ad18d8b2-1878-480d-b52a-6556cd0cabd0
		summarizeBy: none
		sourceColumn: resolver_name

	partition dim_resolver = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_resolver.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"resolver_key", Int64.Type}, {"resolver_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
