table dim_location
	lineageTag: 91442572-95d1-4a00-9688-693bd5602917

	column location_key
		dataType: int64
		isHidden
		lineageTag: 7b86a6c2-13a3-4bdc-9461-3897058cd1c9
		summarizeBy: none
		sourceColumn: location_key

	column Location
		dataType: string
		lineageTag: 02bdd962-dc58-4787-ae33-a5a5fe2b9578
		summarizeBy: none
		sourceColumn: location_name

	partition dim_location = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_location.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"location_key", Int64.Type}, {"location_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
