table dim_category
	lineageTag: 5a9f7ee1-dd46-4e61-b938-d4094c1295f4

	column category_key
		dataType: int64
		isHidden
		lineageTag: 5f9568fe-e080-4cd8-936c-94baf16c85e9
		summarizeBy: none
		sourceColumn: category_key

	column Category
		dataType: string
		lineageTag: 0bea01fd-b5ee-40dc-9a6e-0c011ce736ac
		summarizeBy: none
		sourceColumn: category_name

	column Subcategory
		dataType: string
		lineageTag: 187d4872-e535-4531-8b15-e001cfb5495d
		summarizeBy: none
		sourceColumn: subcategory_name

	partition dim_category = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_category.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"category_key", Int64.Type}, {"category_name", type text}, {"subcategory_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
