table dim_closed_code
	lineageTag: b9904d4b-e8f0-4c9e-9507-d6a16a587461

	column closed_code_key
		dataType: int64
		isHidden
		lineageTag: 30e819b8-efbf-417e-9ce3-093a0633cb81
		summarizeBy: none
		sourceColumn: closed_code_key

	column 'Closed Code'
		dataType: string
		lineageTag: bd2e8bd7-1e86-4567-a536-bd9ce980daa0
		summarizeBy: none
		sourceColumn: closed_code_name

	partition dim_closed_code = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_closed_code.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"closed_code_key", Int64.Type}, {"closed_code_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
