table dim_variant
	lineageTag: 7c0d823f-cfea-4bf4-9ce9-da782902f2a5

	column variant_key
		dataType: int64
		isHidden
		lineageTag: 6123ccf5-93bc-45a7-9042-789f71a89957
		summarizeBy: none
		sourceColumn: variant_key

	column 'Variant Path'
		dataType: string
		lineageTag: aa25b94f-26d8-4918-8790-78a2196cc937
		summarizeBy: none
		sourceColumn: variant_path

	column 'Variant Length'
		dataType: int64
		lineageTag: db664f40-56a0-4090-a790-1707b2f84a5b
		summarizeBy: none
		sourceColumn: variant_length

	column incident_count
		dataType: int64
		lineageTag: 877c9714-d98a-4fe6-85b2-d73f0a0f25af
		summarizeBy: none
		sourceColumn: incident_count

	column 'Variant Rank'
		dataType: int64
		lineageTag: 6a8dbe28-033d-4fe0-8c10-c91c81445b7c
		summarizeBy: none
		sourceColumn: variant_rank

	column is_happy_path
		dataType: boolean
		lineageTag: 9ede4181-34a0-478d-8195-f52513746b65
		summarizeBy: none
		sourceColumn: is_happy_path

	partition dim_variant = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_variant.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"variant_key", Int64.Type}, {"variant_path", type text}, {"variant_length", Int64.Type}, {"incident_count", Int64.Type}, {"variant_rank", Int64.Type}, {"is_happy_path", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
