table dim_priority
	lineageTag: 3f034c64-014e-4dbd-8f2b-4e86dd891048

	column priority_key
		dataType: int64
		isHidden
		lineageTag: 06b2d8be-7421-4417-ad91-32a8cdd97955
		summarizeBy: none
		sourceColumn: priority_key

	column Priority
		dataType: string
		lineageTag: 629c2280-e227-4efe-87c8-1e18634f1593
		summarizeBy: none
		sourceColumn: priority_label
		sortByColumn: priority_rank

	column priority_rank
		dataType: int64
		lineageTag: 17ff4b7a-ba0e-45d9-8ed0-4da9a82c9e88
		summarizeBy: none
		sourceColumn: priority_rank

	column is_high_priority
		dataType: boolean
		lineageTag: 5ad81176-cc0e-4cd9-a87c-8d24f3027dbd
		summarizeBy: none
		sourceColumn: is_high_priority

	partition dim_priority = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_priority.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"priority_key", Int64.Type}, {"priority_label", type text}, {"priority_rank", Int64.Type}, {"is_high_priority", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
