table dim_category
	lineageTag: fb2d1602-5806-41f1-98ed-de6073002146

	column category_key
		dataType: int64
		isHidden
		lineageTag: 2c0785c8-1435-49f5-9125-cc3d6ba51e7e
		summarizeBy: none
		sourceColumn: category_key

	column Category
		dataType: string
		lineageTag: d269e8d0-1c66-46f5-9790-c87332cc89ec
		summarizeBy: none
		sourceColumn: category_name

	column Subcategory
		dataType: string
		lineageTag: 75a902d2-09dd-4e4c-9491-aaff6ab36584
		summarizeBy: none
		sourceColumn: subcategory_name

	partition dim_category = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_category.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"category_key", Int64.Type}, {"category_name", type text}, {"subcategory_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
