table dim_priority
	lineageTag: b2863272-effb-4172-820a-0c8260d3f74b

	column priority_key
		dataType: int64
		isHidden
		lineageTag: c0c2d2ff-31f7-41c3-a3b5-9917785778fd
		summarizeBy: none
		sourceColumn: priority_key

	column Priority
		dataType: string
		lineageTag: 1e0cb677-8549-48e1-922d-5d3e803eb216
		summarizeBy: none
		sourceColumn: priority_label
		sortByColumn: priority_rank

	column priority_rank
		dataType: int64
		lineageTag: 4b0fdd4e-51b4-4a68-8266-18c145053637
		summarizeBy: none
		sourceColumn: priority_rank

	column is_high_priority
		dataType: boolean
		lineageTag: 49d197ae-9d66-4fe9-9683-5ea81c5848c4
		summarizeBy: none
		sourceColumn: is_high_priority

	partition dim_priority = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_priority.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"priority_key", Int64.Type}, {"priority_label", type text}, {"priority_rank", Int64.Type}, {"is_high_priority", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
