table dim_date
	dataCategory: Time
	lineageTag: aa6914d5-c42d-48b2-9f59-0f8eb7b52452

	column date_key
		dataType: int64
		isHidden
		lineageTag: 58a614be-becf-4f08-b83b-276c0104e0cd
		summarizeBy: none
		sourceColumn: date_key

	column Date
		dataType: dateTime
		isKey
		lineageTag: a63f8e3d-b4dc-4372-b0b0-a201507b0b5d
		summarizeBy: none
		sourceColumn: date_value
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 6c7cc7ea-5afb-4546-bd64-f65f8c40a0c8
		summarizeBy: none
		sourceColumn: calendar_year

	column Quarter
		dataType: int64
		lineageTag: 86678b83-985c-4142-8fd3-2e076b5a9a1b
		summarizeBy: none
		sourceColumn: calendar_quarter

	column calendar_month
		dataType: int64
		lineageTag: c7ca6f57-c852-4b1d-908e-dae83d8e2ed0
		summarizeBy: none
		sourceColumn: calendar_month

	column Month
		dataType: string
		lineageTag: 6594b0a1-303b-4259-ac28-f17c9bac5b88
		summarizeBy: none
		sourceColumn: month_name

	column 'Year-Month'
		dataType: string
		lineageTag: 907f6df5-ff2f-40e8-9b34-5f9fb8435c1e
		summarizeBy: none
		sourceColumn: year_month

	column day_of_month
		dataType: int64
		lineageTag: c48b06e2-a05f-48d9-9ade-4d3b0df51d5e
		summarizeBy: none
		sourceColumn: day_of_month

	column day_of_week_num
		dataType: int64
		lineageTag: 5f343ee4-a2cc-4d4f-a80b-bb4dd8c2599a
		summarizeBy: none
		sourceColumn: day_of_week_num

	column Day
		dataType: string
		lineageTag: dc895859-fc24-42ed-8d84-d4afcfe611b7
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		lineageTag: 603dffa4-3488-4a49-b038-5c0666105552
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_date.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date_value", type date}, {"calendar_year", Int64.Type}, {"calendar_quarter", Int64.Type}, {"calendar_month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_month", Int64.Type}, {"day_of_week_num", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
