table dim_contact_type
	lineageTag: 589d0b39-8b7f-4dab-98b8-cec33d29b8fd

	column contact_type_key
		dataType: int64
		isHidden
		lineageTag: 5f89bb5d-fa74-4666-a3c4-9f0c70750492
		summarizeBy: none
		sourceColumn: contact_type_key

	column 'Contact Type'
		dataType: string
		lineageTag: 87384052-9858-4428-988b-4df3d0e05a45
		summarizeBy: none
		sourceColumn: contact_type_name

	column is_self_service
		dataType: boolean
		lineageTag: 1cba7b4e-b7d2-40b2-a0bb-78c5af6dbe1d
		summarizeBy: none
		sourceColumn: is_self_service

	partition dim_contact_type = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_contact_type.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"contact_type_key", Int64.Type}, {"contact_type_name", type text}, {"is_self_service", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
