table dim_date
	dataCategory: Time
	lineageTag: 3163e07a-4527-4f5f-823a-7c1798995287

	column date_key
		dataType: int64
		isHidden
		lineageTag: b50fd475-660d-49e5-9af3-8026ddf21178
		summarizeBy: none
		sourceColumn: date_key

	column Date
		dataType: dateTime
		isKey
		lineageTag: 89474ff0-9a3f-4f9b-a299-2c6c6b0ba737
		summarizeBy: none
		sourceColumn: date_value
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a2fea26c-e2a4-4789-8453-5cc6475f0a38
		summarizeBy: none
		sourceColumn: calendar_year

	column Quarter
		dataType: int64
		lineageTag: 2da9c9f3-9dc4-497f-ac19-7a26baf14a14
		summarizeBy: none
		sourceColumn: calendar_quarter

	column calendar_month
		dataType: int64
		lineageTag: 33916919-bafb-4b21-97f6-06e8f5593773
		summarizeBy: none
		sourceColumn: calendar_month

	column Month
		dataType: string
		lineageTag: 9447efae-0366-4e3c-8a6b-c5be3bcf97ec
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: calendar_month

	column 'Year-Month'
		dataType: string
		lineageTag: 4ba191b2-533b-491e-ad1b-1ebde2975122
		summarizeBy: none
		sourceColumn: year_month

	column day_of_month
		dataType: int64
		lineageTag: a2fd0f84-7bdb-4164-b6a4-cd69a76416f2
		summarizeBy: none
		sourceColumn: day_of_month

	column day_of_week_num
		dataType: int64
		lineageTag: 0923c982-1869-4922-a868-beb138d1cbb5
		summarizeBy: none
		sourceColumn: day_of_week_num

	column Day
		dataType: string
		lineageTag: 48e2204c-631f-40b0-aa09-6c4081e48efd
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week_num

	column is_weekend
		dataType: boolean
		lineageTag: 65ad761f-e56e-4246-a209-d9216445085a
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_date.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date_value", type date}, {"calendar_year", Int64.Type}, {"calendar_quarter", Int64.Type}, {"calendar_month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_month", Int64.Type}, {"day_of_week_num", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
