table dim_resolver
	lineageTag: cd9a23b0-5f69-460a-8841-1039e743b8b9

	column resolver_key
		dataType: int64
		isHidden
		lineageTag: 71b35da2-378f-45c0-990b-f4602cbf4e71
		summarizeBy: none
		sourceColumn: resolver_key

	column Resolver
		dataType: string
		lineageTag: bc0734a6-a779-4f9e-8592-d65fa2bffe75
		summarizeBy: none
		sourceColumn: resolver_name

	partition dim_resolver = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_resolver.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"resolver_key", Int64.Type}, {"resolver_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
