table dim_state
	lineageTag: 1d645320-dead-45b8-a1d6-7f702dfb6a01

	column state_key
		dataType: int64
		isHidden
		lineageTag: dec4cc73-8fac-40e4-9d99-2e5d8959d0fd
		summarizeBy: none
		sourceColumn: state_key

	column State
		dataType: string
		lineageTag: c9014530-b973-4426-bcc1-437e1aeb5c14
		summarizeBy: none
		sourceColumn: state_name
		sortByColumn: state_sort_order

	column 'State Category'
		dataType: string
		lineageTag: 77bfe575-80ea-4be1-bb0f-10e9e6116f31
		summarizeBy: none
		sourceColumn: state_category

	column state_sort_order
		dataType: int64
		lineageTag: 4a8d2b64-efab-49a8-9fcf-4837492eb519
		summarizeBy: none
		sourceColumn: state_sort_order

	column is_waiting_state
		dataType: boolean
		lineageTag: c08f4243-79c4-4a76-a812-659dc178f875
		summarizeBy: none
		sourceColumn: is_waiting_state

	partition dim_state = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_state.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"state_key", Int64.Type}, {"state_name", type text}, {"state_category", type text}, {"state_sort_order", Int64.Type}, {"is_waiting_state", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
