table dim_date
	dataCategory: Time
	lineageTag: 15d8488c-1dac-4a5f-a8b8-ac65e031a80d

	column date_key
		dataType: int64
		isHidden
		lineageTag: 0ef5045e-082f-45eb-aa57-a0b408189cdc
		summarizeBy: none
		sourceColumn: date_key

	column Date
		dataType: dateTime
		isKey
		lineageTag: 71acd931-0759-4742-8de0-05cbf025ffa8
		summarizeBy: none
		sourceColumn: date_value
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2936e0e3-16a9-4c3f-817d-63d25dd2b63f
		summarizeBy: none
		sourceColumn: calendar_year

	column Quarter
		dataType: int64
		lineageTag: bc27407e-4aa3-4a14-915a-1ae67f595f6e
		summarizeBy: none
		sourceColumn: calendar_quarter

	column calendar_month
		dataType: int64
		lineageTag: 09924ad5-f348-480d-95f3-ea28531a6b07
		summarizeBy: none
		sourceColumn: calendar_month

	column Month
		dataType: string
		lineageTag: ae6d551a-ddc0-4729-b944-b223f889e59f
		summarizeBy: none
		sourceColumn: month_name

	column 'Year-Month'
		dataType: string
		lineageTag: 14631de4-970b-4943-bd2d-7b1ccff5b9ff
		summarizeBy: none
		sourceColumn: year_month

	column day_of_month
		dataType: int64
		lineageTag: 69087085-8f5b-49be-bc62-327bfaa5d7a5
		summarizeBy: none
		sourceColumn: day_of_month

	column day_of_week_num
		dataType: int64
		lineageTag: e9cecd17-02ec-4304-b09b-73d02cfea58b
		summarizeBy: none
		sourceColumn: day_of_week_num

	column Day
		dataType: string
		lineageTag: 18d6b374-cf73-497a-915f-63ed0c0c489a
		summarizeBy: none
		sourceColumn: day_name

	column is_weekend
		dataType: boolean
		lineageTag: 1c2ea744-1caa-41fb-94b4-5238f04d750b
		summarizeBy: none
		sourceColumn: is_weekend

	partition dim_date = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_date.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date_value", type date}, {"calendar_year", Int64.Type}, {"calendar_quarter", Int64.Type}, {"calendar_month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_month", Int64.Type}, {"day_of_week_num", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
