table dim_variant
	lineageTag: 08981fc6-6401-489c-aabb-3d8649300f62

	column variant_key
		dataType: int64
		isHidden
		lineageTag: 7effb7a0-5a41-470a-a14f-04ab536c9f7a
		summarizeBy: none
		sourceColumn: variant_key

	column 'Variant Path'
		dataType: string
		lineageTag: 11cb5874-b03d-4fc9-a13b-ffa459b3bce7
		summarizeBy: none
		sourceColumn: variant_path

	column 'Variant Length'
		dataType: int64
		lineageTag: 5bbf456c-8f35-47e5-b784-3664e0ddd35f
		summarizeBy: none
		sourceColumn: variant_length

	column incident_count
		dataType: int64
		lineageTag: ef31a675-da25-469f-9982-a2e5d1cbd466
		summarizeBy: none
		sourceColumn: incident_count

	column 'Variant Rank'
		dataType: int64
		lineageTag: 848f0c54-e1e8-44d4-a6be-73db89c26aed
		summarizeBy: none
		sourceColumn: variant_rank

	column is_happy_path
		dataType: boolean
		lineageTag: 9f3f77c4-8183-465a-aa33-fecc350bfd3b
		summarizeBy: none
		sourceColumn: is_happy_path

	partition dim_variant = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_variant.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"variant_key", Int64.Type}, {"variant_path", type text}, {"variant_length", Int64.Type}, {"incident_count", Int64.Type}, {"variant_rank", Int64.Type}, {"is_happy_path", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
