table dim_assignment_group
	lineageTag: ed5b4b65-9210-4e53-9328-4197c60689ff

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: a559a744-bc7b-4d84-90f7-ecb9dc27583d
		summarizeBy: none
		sourceColumn: assignment_group_key

	column 'Assignment Group'
		dataType: string
		lineageTag: fffb275e-b0cc-49d8-89f9-297ef689cdf9
		summarizeBy: none
		sourceColumn: assignment_group_name

	partition dim_assignment_group = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_assignment_group.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"assignment_group_key", Int64.Type}, {"assignment_group_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
