table dim_assignment_group
	lineageTag: 3e9f38da-a3d3-4b98-ac11-0d2a4cd07c4e

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: cc0f7f4a-f681-41fb-bb52-e9fa689c687b
		summarizeBy: none
		sourceColumn: assignment_group_key

	column 'Assignment Group'
		dataType: string
		lineageTag: efe6678d-34b9-4b9c-8f7c-cc1dc8695310
		summarizeBy: none
		sourceColumn: assignment_group_name

	partition dim_assignment_group = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_assignment_group.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"assignment_group_key", Int64.Type}, {"assignment_group_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
