table dim_closed_code
	lineageTag: 21f924cc-7506-4753-892a-219628007c4b

	column closed_code_key
		dataType: int64
		isHidden
		lineageTag: 24dae641-3972-4c0c-ac69-8d635f6b1d9c
		summarizeBy: none
		sourceColumn: closed_code_key

	column 'Closed Code'
		dataType: string
		lineageTag: 6a57df23-90cb-4994-ad94-18a686106c36
		summarizeBy: none
		sourceColumn: closed_code_name

	partition dim_closed_code = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_closed_code.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"closed_code_key", Int64.Type}, {"closed_code_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
