table dim_location
	lineageTag: a8b351d8-84f9-455c-b243-9bc648854058

	column location_key
		dataType: int64
		isHidden
		lineageTag: 3300c04e-7123-4374-b5c3-89b8f126b698
		summarizeBy: none
		sourceColumn: location_key

	column Location
		dataType: string
		lineageTag: aa131ade-e069-4512-9003-4e2f3d9b173c
		summarizeBy: none
		sourceColumn: location_name

	partition dim_location = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_location.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"location_key", Int64.Type}, {"location_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
