table dim_closed_code
	lineageTag: 078fad10-a28e-4184-a618-cb2598816400

	column closed_code_key
		dataType: int64
		isHidden
		lineageTag: 32b9442a-fce6-40f8-b108-66a8ea4e38eb
		summarizeBy: none
		sourceColumn: closed_code_key

	column 'Closed Code'
		dataType: string
		lineageTag: d2582f35-bb44-4e6c-a93b-36f581410cae
		summarizeBy: none
		sourceColumn: closed_code_name

	partition dim_closed_code = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_closed_code.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"closed_code_key", Int64.Type}, {"closed_code_name", type text}})
				in
					Typed

	annotation PBI_ResultType = Table
