table dim_contact_type
	lineageTag: 78ac6ca1-60c9-417b-a79c-b3277752fbbd

	column contact_type_key
		dataType: int64
		isHidden
		lineageTag: e31bcbc9-71dd-472f-b017-5ee7fcb46b42
		summarizeBy: none
		sourceColumn: contact_type_key

	column 'Contact Type'
		dataType: string
		lineageTag: 368116e4-96f0-458f-8121-7b70b1273519
		summarizeBy: none
		sourceColumn: contact_type_name

	column is_self_service
		dataType: boolean
		lineageTag: 56b2502c-451d-43c1-a4c9-f277e60dd6f2
		summarizeBy: none
		sourceColumn: is_self_service

	partition dim_contact_type = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_contact_type.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"contact_type_key", Int64.Type}, {"contact_type_name", type text}, {"is_self_service", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
