table dim_variant
	lineageTag: ecaa7eb2-4908-4926-8145-c0d8d286900c

	column variant_key
		dataType: int64
		isHidden
		lineageTag: 931c9a51-6f64-43b1-85f4-68bacf315ee7
		summarizeBy: none
		sourceColumn: variant_key

	column 'Variant Path'
		dataType: string
		lineageTag: c7e287ff-9a4e-4527-a09c-ed26d661eba3
		summarizeBy: none
		sourceColumn: variant_path

	column 'Variant Length'
		dataType: int64
		lineageTag: c3d074b7-a322-4c5b-b284-cb08da82b413
		summarizeBy: none
		sourceColumn: variant_length

	column incident_count
		dataType: int64
		lineageTag: b8b6ccff-7a3f-47bf-bd66-a20891d209e7
		summarizeBy: none
		sourceColumn: incident_count

	column 'Variant Rank'
		dataType: int64
		lineageTag: e2da243a-a1a1-4f44-94a4-7c70238c9184
		summarizeBy: none
		sourceColumn: variant_rank

	column is_happy_path
		dataType: boolean
		lineageTag: b3c10ebd-e50c-4f21-91d4-40cc830890d5
		summarizeBy: none
		sourceColumn: is_happy_path

	partition dim_variant = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "dim_variant.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"variant_key", Int64.Type}, {"variant_path", type text}, {"variant_length", Int64.Type}, {"incident_count", Int64.Type}, {"variant_rank", Int64.Type}, {"is_happy_path", type logical}})
				in
					Typed

	annotation PBI_ResultType = Table
