table fact_incident_case
	lineageTag: 80934344-02e7-4454-bc40-0b0e3408884b

	/// Distinct incidents.
	/// Counted at case grain, never event grain - the event table holds 141,707 rows for 24,918 incidents, so counting there would overstate volume roughly 5.7x.
	measure 'Total Incidents' = COUNTROWS ( fact_incident_case )
		formatString: #,0
		lineageTag: b39ec382-534b-40a0-aec4-8b2481930bc9
		displayFolder: 01 Volume

	/// Process steps recorded across all incidents.
	measure 'Total Events' = COUNTROWS ( fact_incident_event )
		formatString: #,0
		lineageTag: 501fe247-1b49-498d-8c77-46ef80bc5301
		displayFolder: 01 Volume

	/// Process touch count.
	/// A rising value means more handling per incident.
	measure 'Avg Events per Incident' = DIVIDE ( [Total Events], [Total Incidents] )
		formatString: #,0.0
		lineageTag: fb72cefb-6333-4409-9c6a-8c0adcef02bc
		displayFolder: 01 Volume

	/// Incidents whose final observed made_sla value was true.
	/// Last-value semantics per DQ-09.
	measure 'SLA Met' = SUM ( fact_incident_case[is_sla_met] )
		formatString: #,0
		lineageTag: 1121dfa5-29b0-44b7-9df4-fb81d4ff12cb
		displayFolder: 02 SLA

	/// Incidents whose final observed made_sla value was false.
	measure 'SLA Breached' = SUM ( fact_incident_case[is_sla_breached] )
		formatString: #,0
		lineageTag: 8ab3e4b7-7e07-4e5c-bad9-9968f1e27841
		displayFolder: 02 SLA

	/// Headline KPI.
	/// Denominator is ALL incidents, not just resolved ones - excluding unresolved incidents would flatter the number by hiding the cases most likely to have breached.
	measure 'SLA Attainment %' = DIVIDE ( [SLA Met], [Total Incidents] )
		formatString: 0.0%
		lineageTag: b0b8d556-41e2-4480-86dc-f126eb6a64cf
		displayFolder: 02 SLA

	/// Complement of attainment.
	/// Held as its own measure so breach-focused visuals do not have to express 1 - x.
	measure 'SLA Breach %' = DIVIDE ( [SLA Breached], [Total Incidents] )
		formatString: 0.0%
		lineageTag: d6d624b9-a496-42d7-b9a8-a8808c7e428b
		displayFolder: 02 SLA

	/// Prior-month attainment.
	/// Requires dim_date to be marked as the date table.
	measure 'SLA Attainment % PM' = CALCULATE ( [SLA Attainment %], DATEADD ( dim_date[Date], -1, MONTH ) )
		formatString: 0.0%
		lineageTag: 927f65b2-8487-4599-8641-85d86b909e08
		displayFolder: 02 SLA

	/// Month-over-month change in percentage points.
	/// Returns blank rather than a misleading full-value delta when there is no prior month.
	measure 'SLA Attainment % MoM' =
				VAR Current = [SLA Attainment %]
				VAR Prior = [SLA Attainment % PM]
				RETURN IF ( NOT ISBLANK ( Prior ), Current - Prior )
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: e8177864-f6e3-4c1a-a6d1-4320c2a9159f
		displayFolder: 02 SLA

	/// The cycle-time denominator.
	/// Shown on the report so the audience can see how many incidents the duration KPIs are actually based on.
	measure 'Incidents with Valid Cycle Time' = SUM ( fact_incident_case[has_valid_resolution_time] )
		formatString: #,0
		lineageTag: c43523ce-69f9-4bd2-84be-3917d136f552
		displayFolder: 03 Cycle Time

	/// Primary cycle-time KPI.
	/// Median rather than mean: the distribution has a long right tail, and the mean (178h) is over eight times the median (22h), so a mean would describe almost no real incident.
	measure 'Median Resolution Hours' =
				CALCULATE (
				    MEDIAN ( fact_incident_case[Resolution Hours] ),
				    fact_incident_case[has_valid_resolution_time] = 1
				)
		formatString: #,0.0
		lineageTag: 7a4b072b-46b1-4889-b4fc-bf5dcef7ddc2
		displayFolder: 03 Cycle Time

	/// Retained alongside the median so the skew is visible rather than hidden.
	measure 'Avg Resolution Hours' =
				CALCULATE (
				    AVERAGE ( fact_incident_case[Resolution Hours] ),
				    fact_incident_case[has_valid_resolution_time] = 1
				)
		formatString: #,0.0
		lineageTag: 97c565b8-4958-46ea-b70b-3c28e477d1c2
		displayFolder: 03 Cycle Time

	/// Same measure in the unit business stakeholders tend to think in.
	measure 'Median Resolution Days' = DIVIDE ( [Median Resolution Hours], 24 )
		formatString: #,0.0
		lineageTag: 233d46b6-5fdb-4423-954e-e0b84c24c2d5
		displayFolder: 03 Cycle Time

	/// Tail risk.
	/// The median describes the typical incident; P90 describes the experience that generates escalations.
	measure 'P90 Resolution Hours' =
				CALCULATE (
				    PERCENTILE.INC ( fact_incident_case[Resolution Hours], 0.9 ),
				    fact_incident_case[has_valid_resolution_time] = 1
				)
		formatString: #,0.0
		lineageTag: 348d3006-d92b-4888-a58a-8a7cda77ae8e
		displayFolder: 03 Cycle Time

	/// Total elapsed time accumulated in the filtered states.
	/// Nulls (the final event of each case, which has no successor) are ignored by SUM, which is the correct behaviour - that time is genuinely unmeasured, not zero.
	measure 'Total Dwell Hours' = SUM ( fact_incident_event[Dwell Hours] )
		formatString: #,0
		lineageTag: 09043dd8-55b2-4a61-a411-3e47a476f26c
		displayFolder: 04 Bottleneck

	/// Mean time an incident sits in a state before moving on.
	measure 'Avg Dwell Hours' = AVERAGE ( fact_incident_event[Dwell Hours] )
		formatString: #,0.0
		lineageTag: f7b00a9b-e428-45ea-a57a-3240a0240c2f
		displayFolder: 04 Bottleneck

	/// Typical dwell.
	/// Diverges sharply from the mean in the Active state, which is the signal that a minority of incidents are stalling there.
	measure 'Median Dwell Hours' = MEDIAN ( fact_incident_event[Dwell Hours] )
		formatString: #,0.0
		lineageTag: 0c9af5c0-53ba-4ed5-8357-ee4de4894f60
		displayFolder: 04 Bottleneck

	/// Elapsed time blocked on a third party: user, vendor, problem or evidence.
	measure 'Waiting Hours' = CALCULATE ( [Total Dwell Hours], dim_state[State Category] = "Waiting" )
		formatString: #,0
		lineageTag: 3fdd089a-1dfd-4df5-bf15-2b12785f7481
		displayFolder: 04 Bottleneck

	/// Elapsed time in New or Active, where the resolver team holds the work.
	measure 'Working Hours' = CALCULATE ( [Total Dwell Hours], dim_state[State Category] = "Working" )
		formatString: #,0
		lineageTag: 2bbed828-fdaf-450a-a632-d390816c7798
		displayFolder: 04 Bottleneck

	/// Share of elapsed time the process is blocked.
	/// Separates a capacity problem (fix by adding people) from a dependency problem (fix by changing the process).
	measure 'Waiting Time %' = DIVIDE ( [Waiting Hours], [Total Dwell Hours] )
		formatString: 0.0%
		lineageTag: ad4f269f-1723-4f06-b6ec-e6855e30bbd1
		displayFolder: 04 Bottleneck

	/// Each state's share of total elapsed time.
	/// REMOVEFILTERS only on dim_state so the denominator still respects date and priority slicers - the ratio stays meaningful inside any filtered view.
	measure '% of Total Elapsed Time' =
				DIVIDE (
				    [Total Dwell Hours],
				    CALCULATE ( [Total Dwell Hours], REMOVEFILTERS ( dim_state ) )
				)
		formatString: 0.0%
		lineageTag: 93885d4f-bbe3-4158-af32-d293ea74d184
		displayFolder: 04 Bottleneck

	/// Incidents handed between groups at least once.
	measure 'Reassigned Incidents' = SUM ( fact_incident_case[is_reassigned] )
		formatString: #,0
		lineageTag: 3cea8045-5a9c-41bd-940b-7e5dec9ff2e7
		displayFolder: 05 Workload

	/// Routing accuracy proxy.
	/// A high rate means work is not reaching the right team first time.
	measure 'Reassignment Rate %' = DIVIDE ( [Reassigned Incidents], [Total Incidents] )
		formatString: 0.0%
		lineageTag: 91080b7b-9160-471f-9584-c63e7f4cc0ae
		displayFolder: 05 Workload

	/// Mean handoffs per incident.
	measure 'Avg Reassignments' = AVERAGE ( fact_incident_case[Reassignment Count] )
		formatString: #,0.00
		lineageTag: ba42dc1c-820a-439d-aeb6-e0e1ed844bf1
		displayFolder: 05 Workload

	/// Absolute handoff volume - the size of the rework pool.
	measure 'Total Reassignments' = SUM ( fact_incident_case[Reassignment Count] )
		formatString: #,0
		lineageTag: cfa104ca-e59d-4b0c-af82-e371498199bf
		displayFolder: 05 Workload

	/// Incidents reopened at least once after being resolved.
	measure 'Reopened Incidents' = SUM ( fact_incident_case[is_reopened] )
		formatString: #,0
		lineageTag: 5e5bd7de-aa95-44ef-b1fa-bb9fcff0c8f2
		displayFolder: 06 Quality

	/// First-time-fix failure rate.
	/// The cleanest available proxy for resolution quality as opposed to resolution speed.
	measure 'Reopen Rate %' = DIVIDE ( [Reopened Incidents], [Total Incidents] )
		formatString: 0.0%
		lineageTag: 95cc4086-ae3d-4410-b1e9-5f3b695e304a
		displayFolder: 06 Quality

	/// Share of incidents resolved with a knowledge article attached.
	measure 'Knowledge Article Usage %' = DIVIDE ( SUM ( fact_incident_case[used_knowledge_article] ), [Total Incidents] )
		formatString: 0.0%
		lineageTag: 9c398080-b063-435b-8db9-7aae3ef3ee6f
		displayFolder: 06 Quality

	/// Number of distinct routing paths in the filtered population.
	/// Process complexity in a single number.
	measure 'Distinct Variants' = DISTINCTCOUNT ( fact_incident_case[variant_key] )
		formatString: #,0
		lineageTag: 5bd9428d-1567-4e69-adf3-73278f016a10
		displayFolder: 07 Process Variants

	/// Incidents following the single most frequent path.
	measure 'Happy Path Incidents' = CALCULATE ( [Total Incidents], dim_variant[Variant Rank] = 1 )
		formatString: #,0
		lineageTag: 463e78d7-d15e-4199-a725-8481a59be53d
		displayFolder: 07 Process Variants

	/// Process conformance.
	/// REMOVEFILTERS on dim_variant keeps the denominator as the whole population even when a variant visual is cross-filtering.
	measure 'Happy Path %' =
				DIVIDE (
				    [Happy Path Incidents],
				    CALCULATE ( [Total Incidents], REMOVEFILTERS ( dim_variant ) )
				)
		formatString: 0.0%
		lineageTag: 9f57a3c8-ccea-432d-9af9-b548fe3bbb2a
		displayFolder: 07 Process Variants

	/// Share of volume on the five dominant paths - the standardised core of the process.
	measure 'Top 5 Variant %' =
				DIVIDE (
				    CALCULATE ( [Total Incidents], dim_variant[Variant Rank] <= 5 ),
				    CALCULATE ( [Total Incidents], REMOVEFILTERS ( dim_variant ) )
				)
		formatString: 0.0%
		lineageTag: 9d56b717-cef5-4831-a5ec-acc4ed3f6eeb
		displayFolder: 07 Process Variants

	/// Share of demand arriving outside 08:00-18:00 Mon-Fri.
	measure 'Out of Hours %' = DIVIDE ( SUM ( fact_incident_case[opened_out_of_hours] ), [Total Incidents] )
		formatString: 0.0%
		lineageTag: 687c81a0-112b-4a04-8194-06a3fee61023
		displayFolder: 08 Demand

	/// Title text for the drill-through page.
	/// SELECTEDVALUE returns the fallback string rather than blanking when more than one incident is in context, so the page header always explains itself.
	measure 'Selected Incident' =
				SELECTEDVALUE (
				    fact_incident_case[Incident Number],
				    "Select a single incident to drill through"
				)
		lineageTag: 370cfbc6-43ab-4043-b073-bfa5ea76048f
		displayFolder: 09 Drill-through

	column case_key
		dataType: int64
		isHidden
		lineageTag: 56def7e9-1626-4bd4-85e2-ba6342da758f
		summarizeBy: none
		sourceColumn: case_key

	column 'Incident Number'
		dataType: string
		lineageTag: 56083973-73c5-4245-8da1-f0e8bc0d0b87
		summarizeBy: none
		sourceColumn: incident_number

	column priority_key
		dataType: int64
		isHidden
		lineageTag: cb170d34-bdad-408e-8106-b46d3d4594f4
		summarizeBy: none
		sourceColumn: priority_key

	column final_state_key
		dataType: int64
		isHidden
		lineageTag: b732af53-b972-4503-87bc-bf13e3387167
		summarizeBy: none
		sourceColumn: final_state_key

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: badbe744-b63c-429c-bc9b-a0f07ee906e1
		summarizeBy: none
		sourceColumn: assignment_group_key

	column category_key
		dataType: int64
		isHidden
		lineageTag: bd73f0e9-1724-4418-90ce-17ef694a7485
		summarizeBy: none
		sourceColumn: category_key

	column contact_type_key
		dataType: int64
		isHidden
		lineageTag: 28a4348b-80a2-451a-b468-17a7f1ef529b
		summarizeBy: none
		sourceColumn: contact_type_key

	column location_key
		dataType: int64
		isHidden
		lineageTag: 22bc9c7e-8849-49b8-bed6-02851afbf126
		summarizeBy: none
		sourceColumn: location_key

	column closed_code_key
		dataType: int64
		isHidden
		lineageTag: e349def4-d7d3-4538-8afe-3c32ed6418a9
		summarizeBy: none
		sourceColumn: closed_code_key

	column resolver_key
		dataType: int64
		isHidden
		lineageTag: 563be109-f625-4ee6-b298-39b1ae2fd6d4
		summarizeBy: none
		sourceColumn: resolver_key

	column variant_key
		dataType: int64
		isHidden
		lineageTag: 1b4da27e-d24a-4a67-a097-05ae5bae2f93
		summarizeBy: none
		sourceColumn: variant_key

	column opened_date_key
		dataType: int64
		isHidden
		lineageTag: 2cec801e-58f0-43f7-9f00-dc3e30f26299
		summarizeBy: none
		sourceColumn: opened_date_key

	column resolved_date_key
		dataType: int64
		isHidden
		lineageTag: dc8efddd-f86d-41d0-80cf-085d310ac915
		summarizeBy: none
		sourceColumn: resolved_date_key

	column impact
		dataType: string
		lineageTag: 4d0b4d79-7aa7-439e-92c5-87e6218f8823
		summarizeBy: none
		sourceColumn: impact

	column urgency
		dataType: string
		lineageTag: 36caacb2-2cd1-447c-a3a2-3921e5a91a20
		summarizeBy: none
		sourceColumn: urgency

	column 'Opened At'
		dataType: dateTime
		lineageTag: 61d6930f-9b01-4e1b-a65e-bc45e4ea4f13
		summarizeBy: none
		sourceColumn: opened_at
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column 'Resolved At'
		dataType: dateTime
		lineageTag: 595bab32-bd33-49a1-bed2-d408c2db344f
		summarizeBy: none
		sourceColumn: resolved_at
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column 'Event Count'
		dataType: int64
		lineageTag: a4f0ab74-58dc-40a3-8b13-0dd36e7908f4
		summarizeBy: none
		sourceColumn: event_count

	column 'Reassignment Count'
		dataType: int64
		lineageTag: 48f7a2bb-ec45-469a-a87a-5c376255b10b
		summarizeBy: none
		sourceColumn: reassignment_count

	column 'Reopen Count'
		dataType: int64
		lineageTag: 15f0bb33-67f7-4da8-aa6e-d09192f88a05
		summarizeBy: none
		sourceColumn: reopen_count

	column modification_count
		dataType: int64
		lineageTag: f85392a0-f248-4f7b-8147-9eefebcdddae
		summarizeBy: none
		sourceColumn: modification_count

	column 'Resolution Hours'
		dataType: double
		lineageTag: 4156e54f-a299-4159-b5d5-8e6849b11b78
		summarizeBy: none
		sourceColumn: resolution_hours

	column hours_in_working_states
		dataType: double
		lineageTag: 824747ef-3958-4769-b6a6-c2c15f503beb
		summarizeBy: none
		sourceColumn: hours_in_working_states

	column hours_in_waiting_states
		dataType: double
		lineageTag: 3845f2a1-6ae4-4fcd-a239-1463dfcd4ce3
		summarizeBy: none
		sourceColumn: hours_in_waiting_states

	column is_sla_met
		dataType: int64
		lineageTag: 983be085-458e-4849-ac14-e6d45d01542d
		summarizeBy: none
		sourceColumn: is_sla_met

	column is_sla_breached
		dataType: int64
		lineageTag: 25e79c5e-497c-4864-bafb-eae0a2109378
		summarizeBy: none
		sourceColumn: is_sla_breached

	column is_reopened
		dataType: int64
		lineageTag: 6e503f2d-4e25-4ae3-b89a-d47ca0a248bf
		summarizeBy: none
		sourceColumn: is_reopened

	column is_reassigned
		dataType: int64
		lineageTag: 3adaf1b7-ad7d-4a82-9a16-94add5ea6432
		summarizeBy: none
		sourceColumn: is_reassigned

	column is_resolved
		dataType: int64
		lineageTag: 53aa37c0-852b-49bb-a0b0-851332ecaeaf
		summarizeBy: none
		sourceColumn: is_resolved

	column has_valid_resolution_time
		dataType: int64
		lineageTag: 51c202bd-4f6a-4a5f-a984-802fd80dfadf
		summarizeBy: none
		sourceColumn: has_valid_resolution_time

	column used_knowledge_article
		dataType: int64
		lineageTag: 19a91c89-57a1-4b64-bdd6-6e305f188904
		summarizeBy: none
		sourceColumn: used_knowledge_article

	column opened_out_of_hours
		dataType: int64
		lineageTag: 680c1013-8ba0-4839-a5b3-89e41ea99cb1
		summarizeBy: none
		sourceColumn: opened_out_of_hours

	column 'Opened Hour'
		dataType: int64
		lineageTag: 66ea7df6-0776-4b27-afdc-c9465fe1a127
		summarizeBy: none
		sourceColumn: opened_hour

	column opened_day_of_week
		dataType: int64
		lineageTag: d8010e23-2475-4ee9-a3ed-b00c4bd03447
		summarizeBy: none
		sourceColumn: opened_day_of_week

	partition fact_incident_case = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "fact_incident_case.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"case_key", Int64.Type}, {"incident_number", type text}, {"priority_key", Int64.Type}, {"final_state_key", Int64.Type}, {"assignment_group_key", Int64.Type}, {"category_key", Int64.Type}, {"contact_type_key", Int64.Type}, {"location_key", Int64.Type}, {"closed_code_key", Int64.Type}, {"resolver_key", Int64.Type}, {"variant_key", Int64.Type}, {"opened_date_key", Int64.Type}, {"resolved_date_key", Int64.Type}, {"impact", type text}, {"urgency", type text}, {"opened_at", type datetime}, {"resolved_at", type datetime}, {"event_count", Int64.Type}, {"reassignment_count", Int64.Type}, {"reopen_count", Int64.Type}, {"modification_count", Int64.Type}, {"resolution_hours", type number}, {"hours_in_working_states", type number}, {"hours_in_waiting_states", type number}, {"is_sla_met", Int64.Type}, {"is_sla_breached", Int64.Type}, {"is_reopened", Int64.Type}, {"is_reassigned", Int64.Type}, {"is_resolved", Int64.Type}, {"has_valid_resolution_time", Int64.Type}, {"used_knowledge_article", Int64.Type}, {"opened_out_of_hours", Int64.Type}, {"opened_hour", Int64.Type}, {"opened_day_of_week", Int64.Type}})
				in
					Typed

	annotation PBI_ResultType = Table
