table fact_incident_event
	lineageTag: 297515e4-5faa-4713-845f-31f3e47b56c7

	column event_key
		dataType: int64
		isHidden
		lineageTag: 77fd145c-53fc-4513-96a0-0ca4d86f331e
		summarizeBy: none
		sourceColumn: event_key

	column case_key
		dataType: int64
		isHidden
		lineageTag: 483aba01-8832-4862-ae63-898fee2eb08b
		summarizeBy: none
		sourceColumn: case_key

	column 'Incident Number'
		dataType: string
		lineageTag: 0e5ebba4-31e2-4098-847f-1ea0a1fcefc2
		summarizeBy: none
		sourceColumn: incident_number

	column state_key
		dataType: int64
		isHidden
		lineageTag: 645ee00f-fe2b-4bfe-8ac3-808db9ddb346
		summarizeBy: none
		sourceColumn: state_key

	column next_state_key
		dataType: int64
		isHidden
		lineageTag: 271bf408-ee7c-44a1-b288-af715853e455
		summarizeBy: none
		sourceColumn: next_state_key

	column priority_key
		dataType: int64
		isHidden
		lineageTag: d205426b-7317-4a95-b714-141308b3934f
		summarizeBy: none
		sourceColumn: priority_key

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: c30384ca-8d97-43b0-91e0-788ea73a9c6f
		summarizeBy: none
		sourceColumn: assignment_group_key

	column event_date_key
		dataType: int64
		isHidden
		lineageTag: 226e6c16-9e8d-4027-87ce-ed9c8f578bf4
		summarizeBy: none
		sourceColumn: event_date_key

	column 'Event Timestamp'
		dataType: dateTime
		lineageTag: 3f13dfe9-eba6-4e52-b7ba-f5f6a6c3b3a1
		summarizeBy: none
		sourceColumn: event_timestamp
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column 'Event Sequence'
		dataType: int64
		lineageTag: 9aa4fbab-95a0-4265-baa2-090817d5bb81
		summarizeBy: none
		sourceColumn: event_seq

	column events_in_case
		dataType: int64
		lineageTag: dbd8b68b-23d2-4e96-a415-b6c385fe3283
		summarizeBy: none
		sourceColumn: events_in_case

	column dwell_minutes
		dataType: double
		lineageTag: 475c050c-0194-4309-99fa-5b2dc3579d85
		summarizeBy: none
		sourceColumn: dwell_minutes

	column 'Dwell Hours'
		dataType: double
		lineageTag: 49ac7495-e585-445f-9964-6fe0b5c72580
		summarizeBy: none
		sourceColumn: dwell_hours

	column is_first_event
		dataType: int64
		lineageTag: 55c3496c-0a6f-4ba4-a2da-36f1c4977883
		summarizeBy: none
		sourceColumn: is_first_event

	column is_last_event
		dataType: int64
		lineageTag: 83f75aca-46ff-49ef-abb7-33082d8fd397
		summarizeBy: none
		sourceColumn: is_last_event

	column is_waiting_event
		dataType: int64
		lineageTag: 0a571510-43a4-4f93-b02b-f2cf42a25d4b
		summarizeBy: none
		sourceColumn: is_waiting_event

	column event_hour
		dataType: int64
		lineageTag: 4e29a3a2-d3d0-4bc5-ae19-306038ccba82
		summarizeBy: none
		sourceColumn: event_hour

	partition fact_incident_event = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "fact_incident_event.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"event_key", Int64.Type}, {"case_key", Int64.Type}, {"incident_number", type text}, {"state_key", Int64.Type}, {"next_state_key", Int64.Type}, {"priority_key", Int64.Type}, {"assignment_group_key", Int64.Type}, {"event_date_key", Int64.Type}, {"event_timestamp", type datetime}, {"event_seq", Int64.Type}, {"events_in_case", Int64.Type}, {"dwell_minutes", type number}, {"dwell_hours", type number}, {"is_first_event", Int64.Type}, {"is_last_event", Int64.Type}, {"is_waiting_event", Int64.Type}, {"event_hour", Int64.Type}})
				in
					Typed

	annotation PBI_ResultType = Table
