table fact_incident_event
	lineageTag: 009af283-6641-4bd8-8679-fa16a7fabe12

	column event_key
		dataType: int64
		isHidden
		lineageTag: b0f1a9f6-bcd8-475c-a9b4-01a555eb5fc3
		summarizeBy: none
		sourceColumn: event_key

	column case_key
		dataType: int64
		isHidden
		lineageTag: 8ef2fbaa-4c6c-4e7d-ae12-992088283268
		summarizeBy: none
		sourceColumn: case_key

	column 'Incident Number'
		dataType: string
		lineageTag: 089c010e-7b69-4822-ad4f-375d16e63d2f
		summarizeBy: none
		sourceColumn: incident_number

	column state_key
		dataType: int64
		isHidden
		lineageTag: 938990f8-67d3-4889-8212-0dd53639f7a5
		summarizeBy: none
		sourceColumn: state_key

	column next_state_key
		dataType: int64
		isHidden
		lineageTag: b9a04f90-5e63-4977-92da-fde69f9947fa
		summarizeBy: none
		sourceColumn: next_state_key

	column priority_key
		dataType: int64
		isHidden
		lineageTag: ea943efc-10c1-4028-9bd0-232b45a47d0f
		summarizeBy: none
		sourceColumn: priority_key

	column assignment_group_key
		dataType: int64
		isHidden
		lineageTag: 0a84efac-e747-49d5-9ca0-ec330907a1b2
		summarizeBy: none
		sourceColumn: assignment_group_key

	column event_date_key
		dataType: int64
		isHidden
		lineageTag: 77577e1f-d304-4a0d-998d-c8d3726969bf
		summarizeBy: none
		sourceColumn: event_date_key

	column 'Event Timestamp'
		dataType: dateTime
		lineageTag: 7b10b153-d594-43f5-b528-c799d6a7dce2
		summarizeBy: none
		sourceColumn: event_timestamp
		formatString: yyyy-mm-dd hh:nn:ss
		annotation SummarizationSetBy = Automatic

	column 'Event Sequence'
		dataType: int64
		lineageTag: e60a6ca5-25fb-45bf-938f-08084ecb7cdd
		summarizeBy: none
		sourceColumn: event_seq

	column events_in_case
		dataType: int64
		lineageTag: c0fd289f-b609-4c03-9664-8b5002f0abfd
		summarizeBy: none
		sourceColumn: events_in_case

	column dwell_minutes
		dataType: double
		lineageTag: 9dcc99c2-d510-4ad5-ae98-c9a6ce1c5a46
		summarizeBy: none
		sourceColumn: dwell_minutes

	column 'Dwell Hours'
		dataType: double
		lineageTag: f31d926d-2bc8-4e1e-a887-da578930cd04
		summarizeBy: none
		sourceColumn: dwell_hours

	column is_first_event
		dataType: int64
		lineageTag: 899f1a1d-4d4c-4a16-aef8-7913176e8c37
		summarizeBy: none
		sourceColumn: is_first_event

	column is_last_event
		dataType: int64
		lineageTag: 879a3dfe-fba1-47d0-b10d-75cd998741a1
		summarizeBy: none
		sourceColumn: is_last_event

	column is_waiting_event
		dataType: int64
		lineageTag: 2b13b44b-1b52-4b1f-885f-e0d2f96866c0
		summarizeBy: none
		sourceColumn: is_waiting_event

	column event_hour
		dataType: int64
		lineageTag: 599758f6-94f8-4bdd-a16f-36f6ce1b224a
		summarizeBy: none
		sourceColumn: event_hour

	partition fact_incident_event = m
		mode: import
		source =
				let
					Source = Csv.Document(
						File.Contents(DataFolder & "fact_incident_event.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"event_key", Int64.Type}, {"case_key", Int64.Type}, {"incident_number", type text}, {"state_key", Int64.Type}, {"next_state_key", Int64.Type}, {"priority_key", Int64.Type}, {"assignment_group_key", Int64.Type}, {"event_date_key", Int64.Type}, {"event_timestamp", type datetime}, {"event_seq", Int64.Type}, {"events_in_case", Int64.Type}, {"dwell_minutes", type number}, {"dwell_hours", type number}, {"is_first_event", Int64.Type}, {"is_last_event", Int64.Type}, {"is_waiting_event", Int64.Type}, {"event_hour", Int64.Type}})
				in
					Typed

	annotation PBI_ResultType = Table
