"""
Step 6 - Execute the analytical queries and publish the results.

Parses sql/02_analysis_queries.sql, runs each named query against the warehouse
and writes every result set to docs/03_analysis_findings.md as a markdown table.

The findings document is therefore GENERATED, never typed. Nothing in it can be
a number somebody remembered wrong, and re-running it after a data change
refreshes every figure in the report and the README at once.

The connection is opened READ ONLY. The analysis layer physically cannot modify
the warehouse, so it can never contend with or corrupt a build.

Usage:
    python src/04_run_analysis.py
"""

from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config as cfg  # noqa: E402

QUERY_FILE = cfg.SQL_DIR / "02_analysis_queries.sql"
OUTPUT_MD = cfg.DOCS_DIR / "03_analysis_findings.md"
OUTPUT_DIR = cfg.PROCESSED_DIR / "analysis"

NAME_MARKER = re.compile(r"^--\s*@name:\s*(\S+)\s*$", re.MULTILINE)


def parse_queries(path: Path) -> list[tuple[str, str]]:
    """Split the SQL file on '-- @name:' markers into (name, sql) pairs."""
    if not path.exists():
        raise FileNotFoundError(f"{path} not found")
    text = path.read_text(encoding="utf-8")

    matches = list(NAME_MARKER.finditer(text))
    if not matches:
        raise ValueError(f"No '-- @name:' markers found in {path}")

    queries: list[tuple[str, str]] = []
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        sql = text[start:end].strip()
        if sql:
            queries.append((m.group(1), sql))
    return queries


def to_markdown(df: pd.DataFrame) -> str:
    """Render a result set as a markdown table without depending on tabulate."""
    if df.empty:
        return "_(no rows)_\n"

    def fmt(v: object) -> str:
        if v is None or (isinstance(v, float) and pd.isna(v)):
            return ""
        if isinstance(v, float):
            return f"{v:,.2f}"
        if isinstance(v, (int,)) and not isinstance(v, bool):
            return f"{v:,}"
        return str(v)

    header = "| " + " | ".join(df.columns) + " |"
    divider = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = [
        "| " + " | ".join(fmt(v) for v in row) + " |"
        for row in df.itertuples(index=False, name=None)
    ]
    return "\n".join([header, divider, *rows]) + "\n"


def main() -> int:
    if not cfg.DUCKDB_PATH.exists():
        raise FileNotFoundError(
            f"{cfg.DUCKDB_PATH} not found. Run: python src/03_build_warehouse.py"
        )

    cfg.DOCS_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    queries = parse_queries(QUERY_FILE)
    print(f"Parsed {len(queries)} named queries from {QUERY_FILE.name}")

    lines: list[str] = [
        "# Step 6 - Analysis Findings\n",
        "> Generated by `src/04_run_analysis.py` from `sql/02_analysis_queries.sql`.",
        "> Every figure below is produced by executing SQL against the warehouse.",
        "> Do not edit by hand.\n",
        f"Generated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC\n",
        "---\n",
    ]

    failures: list[str] = []

    # Read-only: the analysis layer cannot write to the warehouse under any
    # circumstance, so it can never contend with the build.
    con = duckdb.connect(str(cfg.DUCKDB_PATH), read_only=True)
    try:
        for name, sql in queries:
            try:
                df = con.execute(sql).fetch_df()
            except Exception as exc:  # noqa: BLE001 - report and continue
                print(f"  [FAIL] {name}: {exc}")
                failures.append(f"{name}: {exc}")
                lines.append(f"## {name}\n\n**Query failed:** `{exc}`\n")
                continue

            print(f"  [ OK ] {name:<36} {len(df):>4} rows")
            df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
            lines.append(f"## {name}\n")
            lines.append(to_markdown(df))
    finally:
        con.close()

    OUTPUT_MD.write_text("\n".join(lines), encoding="utf-8")

    print(f"\nWrote {OUTPUT_MD.relative_to(cfg.ROOT)}")
    print(f"Wrote {len(queries) - len(failures)} result CSVs to "
          f"{OUTPUT_DIR.relative_to(cfg.ROOT)}")

    if failures:
        print(f"\n{len(failures)} quer(y/ies) failed:")
        for f in failures:
            print(f"  - {f}")
        return 1

    print("Step 6 complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
